# Generated by Django 3.1.7 on 2021-04-07 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default=uuid.uuid1, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(default=uuid.uuid1, max_length=64, unique=True)),
                ('ingredient_unit', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('date', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=32)),
                ('prediction', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predictor.food_item')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predictor.ingredient')),
            ],
        ),
    ]
